- id: nextflow-lint
  name: Nextflow Lint
  description: Run nextflow lint on Nextflow pipeline files
  entry: nextflow-lint-hook
  language: script
  files: \.(nf|config)$
  require_serial: true
  pass_filenames: true
  always_run: false